apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-google-translation-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gke-google-translation-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: gke-google-translation-app
    spec:
      containers:
      - name: google-translation-app
        image: gcr.io/google-samples/hello-app:1.0
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: gke-google-translation-app-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: gke-google-translation-app
